// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjsq5shuRZcXFJis7RYbkB92CBgAA5vY',
    appId: '1:604677483818:web:1ae53dcdb7b72f97888253',
    messagingSenderId: '604677483818',
    projectId: 'nriigbo-a9e30',
    authDomain: 'nriigbo-a9e30.firebaseapp.com',
    databaseURL: 'https://nriigbo-a9e30-default-rtdb.firebaseio.com',
    storageBucket: 'nriigbo-a9e30.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnjsq5shuRZcXFJis7RYbkB92CBgAA5vY',
    appId: '1:604677483818:web:4d0d4e32d5af8de3888253',
    messagingSenderId: '604677483818',
    projectId: 'nriigbo-a9e30',
    authDomain: 'nriigbo-a9e30.firebaseapp.com',
    databaseURL: 'https://nriigbo-a9e30-default-rtdb.firebaseio.com',
    storageBucket: 'nriigbo-a9e30.firebasestorage.app',
  );

}